### ISSUE TITLE
Demo videos chopped out of Automating Sia post

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/spaceduck#44]
There are supposed to be video embeds in the Automating Sia post:

https://github.com/mtlynch/spaceduck/blob/master/_posts/2018-03-08-automating-sia-setup.md#demo

But it looks like they're getting chopped out of the build:

![image](https://user-images.githubusercontent.com/7783288/37888452-92b70696-3095-11e8-8b2e-b341e7ed7a67.png)

**Comment by shredtechular** [comment]
Very interesting... just for my own note when I get to this... able to reproduce with the following steps:

1. load https://blog.spaceduck.io 
2. click on the Automating Sia post

Going directly to https://blog.spaceduck.io/automating-sia-setup/ the issue doesn't occur, nor does refreshing the post directly.  It appears this has something to do with the push state page transitions.  I think there is a config to remove the push state so that may be our best option.

**Comment by mtlynch** [comment]
> I think there is a config to remove the push state so that may be our best option.

The push state is the animation effect after you click a page? Removing that sounds fine to me.

I like that effect, but first priority is having the content render properly. We can circle back to the push state later.
